### PR TITLE
Feature/filter out empty units

### LINKED ISSUE #58: Filter out all rows with no red if user wants to see red
At the moment, all data is shown in app if user click on *Lav måloppnåelse*:

image

Maybe it is better to remove all rows with no red indicators and only keep lines where one or more of the indicators are red?

### PR DESCRIPTION
**Pull request by gabsinator**
closes #58

### CODE REVIEW

**Comment by arnfinn** [comment]
I tried this branch locally (I think, `npm install && sudo npm start`) and it seems to work as expected, except that some of the registry lines are visible even if they have no indicators.

For instance `Tromsø` and `red` will show "Norsk hjerneslagregister", see screenshot:
image

**Comment by gabsinator** [comment]
> I tried this branch locally (I think, `npm install && sudo npm start`) and it seems to work as expected, except that some of the registry lines are visible even if they have no indicators.
> 
> For instance `Tromsø` and `red` will show "Norsk hjerneslagregister", see screenshot:
> image

Ah, didn't think about the "headlines", I'll look into that asap.

**Comment by gabsinator** [comment]
> I tried this branch locally (I think, `npm install && sudo npm start`) and it seems to work as expected, except that some of the registry lines are visible even if they have no indicators.
> 
> For instance `Tromsø` and `red` will show "Norsk hjerneslagregister", see screenshot:

Should "Lav DG" and "No data" both also result in hiding? 
image

**Comment by arnfinn** [comment]
> Should "Lav DG" and "No data" both also result in hiding?

Yes

**Comment by gabsinator** [comment]
> I tried this branch locally (I think, `npm install && sudo npm start`) and it seems to work as expected, except that some of the registry lines are visible even if they have no indicators.
> 
> For instance `Tromsø` and `red` will show "Norsk hjerneslagregister", see screenshot:
> image



> > Should "Lav DG" and "No data" both also result in hiding?
> 
> Yes

Almost there, have another question: 
Do we want to filter away the Nation column, when we have no selected treatment units? E.g. Should we remove "Andel pasienter som har fått utført årskontroll" in the image below?
image

**Comment by arnfinn** [comment]
> Almost there, have another question:
> Do we want to filter away the Nation column, when we have no selected treatment units? E.g. Should we remove "Andel pasienter som har fått utført årskontroll" in the image below?
> image

Yes, I think we want that. Better keep it consistent.

**Comment by gabsinator** [comment]
> 
> Yes, I think we want that. Better keep it consistent.

Can you try again? :)

**Comment by arnfinn** [comment]
> > Yes, I think we want that. Better keep it consistent.
> 
> Can you try again? :)

Looks perfect for `Nation` column. Locally I am not able to make it work when I have picked units.

As an example:

- original data:
image

- After red filter:
image

**Comment by gabsinator** [comment]
> > > Yes, I think we want that. Better keep it consistent.
> > 
> > 
> > Can you try again? :)
> 
> Looks perfect for `Nation` column. Locally I am not able to make it work when I have picked units.
> 

Ah! Nation should not be filtered by thresholds. Should work as intended now, you can test it, I'm gonna finish up and prepare for review.

**Comment by arnfinn** [comment]
Looks like it is working fine now.

**Review by KristianBjornstad — APPROVED** [review]
Good job!

**Pull request merged**
