### PR TITLE
Add a refactored version of the barchart as a component

### LINKED ISSUE #55: Show all treatment units in bar chart
Add the possibility to plot all treatment units in bar chart.

Current plot:

image

How it is now in Power BI (https://www.kvalitetsregistre.no/registers/476/resultater):

image

Either add button to bar chart *Vis alle*, to show all hospitals, or make it the default.

The units that is picked and the national numbers should be highlighted.

### PR DESCRIPTION
**Pull request by LarsJK**
In order to render all TU's in the Barnhart it needs to have a flexible height.

I also wanted to separate d3 code from business logic.

closes #55

### CODE REVIEW

**Review by gabsinator — APPROVED** [review]

**Comment by arnfinn** [comment]
Great!

Some wishes:
- Sort the hospitals, so the one with largest values are on the top
- Skip showing HF and RHF, if possible.
- Maybe show the national numbers, with another color?

**Comment by arnfinn** [comment]
One more thing I noticed is that the line chart now re-zoom when I push "Vis målnivå". The bar chart is not doing that, thus is ok.

**Comment by LarsJK** [comment]
Thanks for the quick review @arnfinn! Will look into it.

**Comment by LarsJK** [comment]
@arnfinn I removed hf and rhf and added nationals, and sorted by value.

Used the darker color for national and a opacity of .5 on bars that are not selected TU's if any are selected:

image

Will fix the linechart next

**Review by gabsinator — APPROVED** [review]

**Comment by arnfinn** [comment]
> @arnfinn I removed hf and rhf and added nationals, and sorted by value.
> 
> 
> 
> Used the darker color for national and a opacity of .5 on bars that are not selected TU's if any are selected:
> 
> 
> 
> image
> 
> 
> 
> Will fix the linechart next

Perfect:)

**Comment by LarsJK** [comment]
This is ready now. Would like to add somme tests for the LineChart but will prioritize the API for now..

**Review by gabriofr — APPROVED** [review]
Looks good to me :) 
When the PRs are merged we should discuss where we want to keep our test builders and helpers?

**Pull request merged**
